import "./spec/user-story-1.test.js"
import "./spec/user-story-2.test.js"
import "./spec/user-story-3.test.js"
import "./spec/user-story-4.test.js"
import "./spec/user-story-5.test.js"
import "./spec/user-story-6.test.js"